stages:
  - build

# Étape pour construire l'image Docker
build_image:
  stage: build
  image: docker:latest  # Utilise l'image officielle Docker pour l'exécution du pipeline
  services:
    - docker:dind  # Utilise Docker-in-Docker pour la construction de l'image
  script:
    - echo "Building Docker image"
    # Si votre Dockerfile est dans un sous-dossier (par exemple, docker/), mettez le bon chemin ici
    - docker build .
