stages:
  - build

# Étape pour construire l'image Docker
build_image:
  stage: build
  image: docker:20.10.16  # image client docker
  services:
    - name: docker:20.10.16-dind
      command: ["--tls=false"]   # désactive TLS, plus simple pour commencer
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""       # désactive TLS auto
  script:
    - echo "Building Docker image"
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
