name: Build and Push Docker image

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch: # permet aussi de déclencher à la main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        r_version: [ 4.1,4.1.0,4.1.1,4.1.2,4.1.3,4.2,4.2.0,4.2.1,4.2.2,4.2.3,4.3,4.3.0,4.3.1,4.3.2,4.3.3,4.4,4.4.0,4.4.1,4.4.2,4.4.3,4.5,4.5.0,4.5.1 ]

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update Dockerfile and renv.lock
        run: |
          sed -i "s/^FROM rocker\/r-ver:.*/FROM rocker\/r-ver:${{ matrix.r_version }}/" Dockerfile

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rjdverse:R-${{ matrix.r_version }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rjdverse:R-${{ matrix.r_version }}-3.5.1

      - name: Tag latest
        if: matrix.r_version == '4.5.1'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rjdverse:latest